service: remote

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  apolloServer:
    handler: functions/apolloServer.handler
    events:
      - http:
          authorizer:
            authorizerId:
              Ref: ApiGatewayAuthorizer
            type: COGNITO_USER_POOLS
          cors: true
          method: post
          path: graphql

package:
  individually: true

plugins:
  - serverless-webpack

provider:
  apiGateway:
    minimumCompressionSize: 0
  iamRoleStatements:
    - Action:
        - dynamodb:GetItem
        - dynamodb:Query
      Effect: Allow
      Resource:
        - Fn::GetAtt: [MoviesTable, Arn]
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  stage: prod

resources:
  - ${file(resources/aws/cognito.yml)}
  - ${file(resources/aws/dynamodb.yml)}
