service: remote

provider:
  name: aws
  region: us-west-1
  runtime: nodejs8.10
  apiGateway:
    minimumCompressionSize: 0
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        - 'arn:aws:dynamodb:us-west-1:*:table/Movies'
        - 'arn:aws:dynamodb:us-west-1:*:table/Movies/*'

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true

functions:
  graphql:
    handler: handler.apolloServer
    events:
      - http:
          cors: true
          method: post
          path: graphql
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApolloServerAuthorizer

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}
        GenerateSecret: false
        UserPoolId:
          Ref: CognitoUserPool

    ApolloServerAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: ${self:service}
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [CognitoUserPool, Arn]
        IdentitySource: method.request.header.Authorization

    MoviesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Movies
        KeySchema:
          - AttributeName: ReleaseYear
            KeyType: HASH
          - AttributeName: CreatedAt
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: CreatedAt
            AttributeType: N
          - AttributeName: ReleaseYear
            AttributeType: N
          - AttributeName: Title
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
