service: remote

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  authorizeUser:
    handler: handler.authorizeUser
    environment:
      COGNITO_URL:
        Fn::Sub: https://cognito-idp.${self:provider.region}.amazonaws.com
      USER_POOL_ID:
        Ref: CognitoUserPool

  graphql:
    handler: handler.apolloServer
    events:
      - http:
          authorizer:
            authorizerId:
              Ref: ApiGatewayAuthorizer
            type: COGNITO_USER_POOLS
          cors: true
          method: post
          path: graphql

package:
  individually: true

plugins:
  localPath: ./plugins
  modules:
    - serverless-version-functions
    - serverless-webpack

provider:
  apiGateway:
    minimumCompressionSize: 0
  iamRoleStatements:
    - Action:
        - dynamodb:GetItem
        - dynamodb:Query
      Effect: Allow
      Resource:
        - Fn::GetAtt: [MoviesTable, Arn]
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  stage: prod

resources:
  - ${file(resources/aws/cloudfront.yml)}
  - ${file(resources/aws/cognito.yml)}
  - ${file(resources/aws/dynamodb.yml)}
  - ${file(resources/aws/s3.yml)}
